### ISSUE TITLE
Pulling docker images

### ISSUE THREAD

**Issue by fenisha29** [Ultimagen/healthomics-workflows#8]
Hello I am trying to run the efficient dv workflow specifically the howto-germline-calling-efficient-dv.md. I am trying to pull the docker images for make_example using either of the two code below and I keep getting permission denied error. 
us-central1-docker.pkg.dev/ganymede-331016/ultimagen/make_examples:2.2.1
or
337532070941.dkr.ecr.us-east-1.amazonaws.com/make_examples:2.2.1

Could you help me fix this problem? (base) fs740@MGB % docker pull us-central1-docker.pkg.dev/ganymede-331016/ultimagen/make_examples:2.2.1

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview us-central1-docker.pkg.dev/ganymede-331016/ultimagen/make_examples:2.2.1
Error response from daemon: Head "https://us-central1-docker.pkg.dev/v2/ganymede-331016/ultimagen/make_examples/manifests/2.2.1": denied: Permission "artifactregistry.repositories.downloadArtifacts" denied on resource "projects/ganymede-331016/locations/us-central1/repositories/ultimagen" (or it may not exist)

**Comment by avigailmo** [comment]
all docker issues were fixed in release v1.13.4
